# Generated by Django 5.2.8 on 2026-09-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_phishingdetection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandbox_table',
            name='behaviour_summary',
            field=models.TextField(),
        ),
    ]
